//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lamode
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdditionalUserInfo
    {
        public string Id { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<decimal> Height { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public string ColorEyes { get; set; }
        public string TellUsMore { get; set; }
        public Nullable<bool> Experience { get; set; }
        public Nullable<bool> NudePhoto { get; set; }
        public string Nationality { get; set; }
        public string ZipCode { get; set; }
        public Nullable<decimal> Bust { get; set; }
        public Nullable<decimal> Hips { get; set; }
        public Nullable<decimal> Dress { get; set; }
        public Nullable<decimal> Waist { get; set; }
        public Nullable<decimal> Cup { get; set; }
        public Nullable<decimal> Shoe { get; set; }
        public string CompanyName { get; set; }
        public string Gender { get; set; }
        public string Website { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
